version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mediqueue_mongo_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - mediqueue_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mediqueue_backend_dev
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongo:27017/mediqueue
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mediqueue_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mediqueue_frontend_dev
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mediqueue_net

volumes:
  mongo_data_dev:

networks:
  mediqueue_net:
    driver: bridge
